### ISSUE TITLE
Add default Prettier YAML config file support

### ISSUE THREAD

**Issue by antonioribeiro** [cgabriel5/prettier-cli-watcher#7]
Can I just use my own `.prettierrc.yml` and add the paths to be watched to it? 

I don't want a second Prettier config file on our project files, and some people will not use prettier-cli-watcher, they can just use their IDEs with Prettier's default config. So, having and maintaining two different files is pretty dangerous if you have a lot of people working on a project. At some point they will be out of sync and we will have a lots of "Fixing coding style" commit messages in our repository.

I agree we need something to configure paths, but it would be nice to be able to use our own prettier YAML config file and just add things to it:

![image](https://user-images.githubusercontent.com/3182864/80863167-b774b800-8c7a-11ea-8be9-7dca1fefe80f.png)

See how this is beautiful and clean? Like Prettier!
Unfortunately JSON is too verbose and doesn't supports comments.

I tried it without the config parameter but I got:

```
$ prettier-cli-watcher
/Users/antonioribeiro/code/flv/flv-website/node_modules/prettier-cli-watcher/src/params.js:101
	path = path.replace(/^(\.?\/)|\/$/g, "");
	            ^

TypeError: Cannot read property 'replace' of undefined
    at preppath (/Users/antonioribeiro/code/flv/flv-website/node_modules/prettier-cli-watcher/src/params.js:101:14)
    at module.exports (/Users/antonioribeiro/code/flv/flv-website/node_modules/prettier-cli-watcher/src/params.js:137:25)
    at Object.<anonymous> (/Users/antonioribeiro/code/flv/flv-website/node_modules/prettier-cli-watcher/src/index.js:15:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cgabriel5** [comment]
The error should _definitely_ be handled better but it's caused by not providing a config path.

At the moment only a `.json` prettier config file is supported. However, it would be good to support `.yaml`/`.yml` files as well.

When you say:
> Can I just use my own .prettierrc.yml and **add the paths to be watched to it**?

Maybe I am misunderstanding but multiple paths cannot be watched. Every `prettier-cli-watcher` instance watches a single path (i.e. ideally the project root directory) and runs prettier on the modified files. If multiple paths need to be watched, multiple instances need to be run. 

Out of curiosity, what is your use case? Most people use their text editor/IDE to prettify their files but I wanted a way to run prettier without having to meddle with text editor plugins. This repo could use some updating/improvements. I'll see what I can do.

**Comment by cgabriel5** [comment]
@antonioribeiro I re-worked the project and have simplified things a great deal. 

Like prettier itself, the project's prettier config file is now auto-located and loaded with [cosmiconfig](https://github.com/davidtheclark/cosmiconfig). This means the config file may now be a: `.json`, `.js`, `.yaml`, `.yml`, or `.toml` file. Ignoring paths is now done through a [`prettierignore`](https://prettier.io/docs/en/ignore.html#ignoring-files) file. It too is auto-located and loaded.

Take a look at the docs [configuration files section](https://github.com/cgabriel5/prettier-cli-watcher#configuration-files) for more details.

To list the config file/prettierignore being used run with the `--setup`: `$ prettier-cli-watcher --setup`.
